### ISSUE TITLE
Build with hdf5 -2.1.1 fails

### ISSUE THREAD

**Issue by junghans** [LLNL/Silo#543]
From https://bugzilla.redhat.com/show_bug.cgi?id=2459406:
```
/builddir/build/BUILD/Silo-4.12.0-build/Silo-4.12.0/src/hdf5_drv/silo_hdf5.c:955:60: error: passing argument 5 of ‘db_hdf5_put_cmemb’ from incompatible pointer type [-Wincompatible-pointer-types]
  955 |         db_hdf5_put_cmemb(_mt, #NAME, OFFSET(_m, NAME), 1, &_size, _tmp_m);   \
      |                                                            ^~~~~~
      |                                                            |
      |                                                            hsize_t * {aka long unsigned int *}
```

[build.log for amd64](https://github.com/user-attachments/files/26855775/build.log.zip)

**Comment by markcmiller86** [comment]
@junghans I believe this is corrected on the `HEAD` of the `4.12RC` branch. 

I just built that against HDF5-2.1.1 and ran `make test` and all tests pass (except for checksum test).

If you have an opportunity to try, can you build against `HEAD` of `4.12RC` branch?

Also, FYI...am planning on cutting a `4.12.1` release in the next week or two at the latest.

**Comment by opoplawski** [comment]
In my test it builds with 2 test failures:
```
        Start 163: test-scale-quadvar-hdf5

163: Test command: /usr/bin/cmake "-E" "env" "/home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests/bin/test_scale_quadvar"
163: Working Directory: /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests
163: Environment variables: 
163:  PYTHONPATH=/home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/lib64:
163:  LD_PRELOAD=:
163:  ASAN_OPTIONS=detect_leaks=0
163: Test timeout computed to be: 1500
163/176 Test #163: test-scale-quadvar-hdf5 ............***Failed    0.07 sec
```
and 
```
        Start 160: checksums

160: Test command: /usr/bin/cmake "-E" "env" "PATH=/usr/bin:/home/orion/.local/bin:/home/orion/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/sbin:/usr/sbin" "ASAN_OPTIONS=detect_leaks=0" "/home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests/bin/checksums"
160: Working Directory: /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests
160: Test timeout computed to be: 1500
160/176 Test #160: checksums ..........................***Failed    2.13 sec
```

**Comment by markcmiller86** [comment]
@opoplawski thanks for report. I suspect that means the `CMakeLists.txt` logic is not quite right for that test. That is a brand new test just added to the `4.12RC` branch last week. Can you please share the CMake command you used?

**Comment by markcmiller86** [comment]
Oh, and `checksum` test always fails on HDF5 versions > 14.4 due to a bug in HDF5

**Comment by opoplawski** [comment]
```
+ /usr/bin/cmake -S . -B redhat-linux-build -G Ninja -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_FULL_SBINDIR:PATH=/usr/bin -DCMAKE_INSTALL_SBINDIR:PATH=bin -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_TESTING=ON -DSILO_ENABLE_SHARED=ON -DSILO_ENABLE_SILOCK=ON -DSILO_ENABLE_SILEX=ON -DSILO_ENABLE_BROWSER=ON -DSILO_ENABLE_FORTRAN=ON -DSILO_ENABLE_HDF5=ON -DSILO_ENABLE_JSON=OFF -DSILO_ENABLE_PYTHON_MODULE=ON -DSILO_INSTALL_PYTHONDIR=/usr/lib/python3.14/site-packages -DSILO_ENABLE_TESTS=ON -DCMAKE_SKIP_INSTALL_RPATH=ON -DSILO_BUILD_FOR_BSD_LICENSE=ON
-- The CXX compiler identification is GNU 16.0.1
-- The C compiler identification is GNU 16.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found HDF5: hdf5-shared (found version "2.1.1")
..
-- The Fortran compiler identification is GNU 16.0.1
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: /usr/bin/gfortran - skipped
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib64/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Found WrapVulkanHeaders: /usr/include
-- Found Python: /usr/bin/python3.14 (found version "3.14.4") found components: Interpreter Development Development.Module Development.Embed
-- Configuring done (7.3s)
```

**Comment by markcmiller86** [comment]
Thanks for CMake info. I am unable to reproduce the `test-scale-quadvar-hdf5 ` failure. I do see `checksum` failure but expect that due to a bug in HDF5 >= 1.14.4

I am building on macOS and so made some adjustments to your CMake command...

```
env PATH=${PATH}:/path/to/python/bin/dir /path/to/cmake \
-DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG \
-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
-DCMAKE_INSTALL_DO_STRIP:BOOL=OFF \
-DCMAKE_INSTALL_PREFIX:PATH=`pwd`/my_install \
-DLIB_SUFFIX=64 \
-DBUILD_SHARED_LIBS:BOOL=ON \
-DBUILD_TESTING=ON \
-DSILO_ENABLE_SHARED=ON \
-DSILO_ENABLE_SILOCK=ON \
-DSILO_ENABLE_SILEX=ON \
-DSILO_ENABLE_BROWSER=ON \
-DSILO_ENABLE_FORTRAN=ON \
-DSILO_ENABLE_HDF5=ON \
-DSILO_ENABLE_JSON=OFF \
-DSILO_ENABLE_PYTHON_MODULE=ON \
-DSILO_ENABLE_TESTS=ON \
-DSILO_BUILD_FOR_BSD_LICENSE=ON \
-DSILO_HDF5_DIR:PATH=/path/to/hdf5-2.1.1/install \
-DSILO_ENABLE_FORTRAN:BOOL=OFF \
-DCMAKE_PREFIX_PATH:PATH=/path/to/mpich/install \
-DSILO_QT6_DIR:PATH=/path/to/qt/install \
..
```

In my build, CMake ignored these...

```
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_Fortran_FLAGS_RELEASE
    CMAKE_INSTALL_DO_STRIP
    LIB_SUFFIX
```

Also, you had `-DSILO_INSTALL_PYTHONDIR=/usr/lib/python3.14/site-packages` which is not a recognized SILO CMake variable. For Silo's CMake, you just have to have the required python interpreter in your path...which is why the CMake command I share above includes `env PATH=${PATH}:/path/to/python/bin/dir`.

I also disabled Fortran because I don't have that on my macOS system. This should NOT effect the tests you reported as failed. 

Finally, I needed to specify path to `mpich` install because the HDF5 install I was using was configured for parallel.

```
.
.
.
148/162 Test #148: test-write-py-hdf5 ..................   Passed    0.20 sec
        Start 149: test-scale-quadvar-hdf5
149/162 Test #149: test-scale-quadvar-hdf5 .............   Passed    0.27 sec
        Start 150: multi_file-reset
150/162 Test #150: multi_file-reset ....................   Passed    0.20 sec
        Start 151: test-read-py
151/162 Test #151: test-read-py ........................   Passed    0.19 sec
        Start 152: multi_file-hdf-friendly
152/162 Test #152: multi_file-hdf-friendly .............   Passed    0.18 sec
        Start 153: test-read-py-hdf5
153/162 Test #153: test-read-py-hdf5 ...................   Passed    0.19 sec
        Start 154: test-error-py
154/162 Test #154: test-error-py .......................   Passed    0.19 sec
        Start 155: testonehex
155/162 Test #155: testonehex ..........................   Passed    0.32 sec
        Start 156: testonehex-hdf5
156/162 Test #156: testonehex-hdf5 .....................   Passed    0.29 sec
        Start 157: test_mat_compression-basic
157/162 Test #157: test_mat_compression-basic ..........   Passed    0.14 sec
        Start 158: test_mat_compression-dense
158/162 Test #158: test_mat_compression-dense ..........   Passed    0.02 sec
        Start 159: test_mat_compression-basic-hdf5
159/162 Test #159: test_mat_compression-basic-hdf5 .....   Passed    0.02 sec
        Start 160: test_mat_compression-dense-hdf5
160/162 Test #160: test_mat_compression-dense-hdf5 .....   Passed    0.02 sec
        Start 161: test_mat_compression-gzip-hdf5
161/162 Test #161: test_mat_compression-gzip-hdf5 ......   Passed    0.02 sec
        Start 162: test_mat_compression-zfp-hdf5
162/162 Test #162: test_mat_compression-zfp-hdf5 .......   Passed    0.01 sec

99% tests passed, 1 tests failed out of 162

Label Time Summary:
compression    =   2.45 sec*proc (7 tests)
hdf5           =   5.50 sec*proc (65 tests)
multi          =  24.58 sec*proc (24 tests)
pdb            =   9.86 sec*proc (52 tests)
python         =   1.97 sec*proc (8 tests)

Total Test time (real) =  66.90 sec

The following tests FAILED:
	146 - checksums (Failed)
Errors while running CTest
Output from these tests are in: /Users/miller86/silo/Silo/build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

**Comment by markcmiller86** [comment]
@opoplawski my apologies but I am incorrect on one issue, above. `-DSILO_INSTALL_PYTHONDIR` is a valid Silo CMake variable. I got confused because it does NOT appear in the top-level `CMakeLists.txt` file. But, it *DOES APPEAR** in the `tools/python/CMakeLists.txt` file and is intended to hold the destination install point for the Silo python module, `Silo.so`.

**Comment by opoplawski** [comment]
Is there any way to get `test-scale-quadvar-hdf5` to output *why* it failed?  It's not very helpful with it's output.

**Comment by markcmiller86** [comment]
Yeah, I agree. That is partly a limitation of CTest.

You can go look at CTest logs. They should be at `./Testing/Temporary/LastTest.log` relative from wherever you triggered testing from (top or test dir).

If you are trigging testing using `make test`, then try `make test ARGS="--output-on-failure"`.

If you are trigging using `ctest` directly, then `ctest --output-on-failure`.

Finally, you can add `-x` to first line of `test/bin/test_scale_quadvar` as in...

```
#!/bin/sh -x
```

**Comment by markcmiller86** [comment]
BTW...if you are running tests in parallel, I do see sporadic issues with some of the python tests in parallel. There is something wrong with the CMakeLists.txt logic for them that is causing them to sometimes stomp on each other during parallel testing. Best to run tests without any parallel.

**Comment by opoplawski** [comment]
The LastTest.log seems just as terse:
```
163/176 Test: test-scale-quadvar-hdf5
Command: "/usr/bin/cmake" "-E" "env" "/home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests/bin/test_scale_quadvar"
Directory: /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests
"test-scale-quadvar-hdf5" start time: Apr 19 20:42 MDT
Output:
----------------------------------------------------------
<end of output>
Test time =   0.07 sec
----------------------------------------------------------
Test Failed.
"test-scale-quadvar-hdf5" end time: Apr 19 20:42 MDT
"test-scale-quadvar-hdf5" time elapsed: 00:00:00
```
Seems like it's an issue with the test, and indeed I see with `bash -x ./bin/test_scale_quadvar`:
```
+ env PYTHONPATH=/home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/lib64 /usr/bin/python3 /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests/bin/scale_quadvar.py
+ result=0
+ /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/bin/browser --proper-exit-code -q -e scaled_data scale_quadvar.silo
+ '[' 1 -ne 0 ']'
+ result=1
+ exit 1
```
and the output of the commands are sent to /dev/null:
```
#
# Use python module to create data with no special features 
#
env PYTHONPATH=$(dirname $silo_pyso) $pycmd $scale_quadvar_py 1>/dev/null 2>&1

#
# Now, run browser and make sure we don't get any errors in the diff
#
result=0
$browser --proper-exit-code -q -e scaled_data scale_quadvar.silo 1>/dev/null 2>&1
```
So we don't see:
```
$ env PYTHONPATH=/home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/lib64 /usr/bin/python3 /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/tests/bin/scale_quadvar.py
DBOpen: File not found or invalid permissions: box_in_a_box.silo
DBWriteObject: Low-level function call failed: Cannot customize standard object
DBWriteObject: Low-level function call failed: Cannot customize standard object
DBWriteObject: Low-level function call failed: Cannot customize standard object
$ /home/orion/fedora/Silo/Silo-4.12.0-build/Silo-9d87e519b93612ac5a8e6f872fcd88e105b15fa6/redhat-linux-build/bin/browser --proper-exit-code -q -e scaled_data scale_quadvar.silo
DBGetObject: Object not found: scaled_data
***ERROR***                 = file_deref: `/scaled_data' is not a database object in `scale_quadvar.silo'
```
I'll note that the python script does open bin/box_in_a_box.silo after the first DBOpen message.

**Comment by markcmiller86** [comment]
Hmmm... I think this hash you are using is potentially the problem, 9d87e519b93612ac5a8e6f872fcd88e105b15fa6. That appears to me to be a commit to `main`. I am hoping you are building against head of branch, `4.12RC`.

That said, your experience is pointing out something confusing to me as well. That error message about `Cannot customize standard object` can only be arrived at due to some poorly constructed HDF5 version checking logic...which I thought I had corrected everywhere and am now seeing additional cases I didn't catch on `main`.

So, your experience has alerted me to something I need to fix.

All that said, I am pretty convinced you are not building against head of `4.12RC`. Can you please take a closer look and confirm one way or the other?

**Comment by markcmiller86** [comment]
FYI...in #548, I did fix the issue on `main` your experience alerted me to and I mentioned above.

So, if you try again with current `HEAD` (of `main` if that is your intention), the `test-scale-quadvar-hdf5` should pass. 

The `checksum` test will still fail for reasons as described previously.

**Comment by opoplawski** [comment]
Sorry, I missed earlier that you specified the 4.12RC branch.  I grabbed the head of that and indeed only the checksums test fails.  I also verified that with the latest main as well.  Thanks.

**Comment by junghans** [comment]
@markcmiller86 any new on the 4.12.1 release?

**Comment by markcmiller86** [comment]
> [@markcmiller86](https://github.com/markcmiller86) any new on the 4.12.1 release?

Trying to get ci matrix of compilers and hdf5 versions working...at least as part of pre-release testing.
